main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.signup, name='signup'),
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def home(request):
    return render(request, 'main/home.html')

def log_in(request):
    if (request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        success = False
        if user is not None:
            login(request, user)
            success = True
            return render(request, 'main/home.html', {'success':success})
        
        else:
            
            return render(request, 'main/login.html', {'success':success})
    else:  
        return render(request, 'main/login.html')

def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')

def signup(request):
    if(request.method == "POST"):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        return render(request, 'main/signup.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<style>
    p{
        text-align: center;
    }
    
</style>
{% endblock meta %}

{% block content %}
{% if user.is_authenticated %}
<h2 style="text-align: center;">Hi, {{ user.username }}!</h2>
<p><a href="{% url 'main:logout' %}">Log Out</a></p>
{% else %}
<h2 style="text-align: center;">You are not logged in</h2>
<p><a href="{% url 'main:login' %}">Log In</a></p>
{% endif %}
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<style>
    .form-container{
        padding:10;
        position:relative;
        top:5%;
        width:50%;
        margin:auto;
    }
    
</style>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:login' %}" method="post">
    {% csrf_token %}
    <div class="form-container">
        <h2>Log in</h2>   
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" name="username" id="username">
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
            </div>
            <input type="password" class="form-control" placeholder="Password" name="password" id="password">
        </div>
        <button type="submit" class="btn btn-dark">Log in</button>
    {% if success == False %}
    <p style="color: red;">Login Failed</p>
    {% endif %}
    <p></p>
    <p>Don't have an account? <a href="{% url 'main:signup' %}">Sign Up</a></p>
    </div>
</form>
{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
<style>
    .form-container{
        padding:10;
        position:relative;
        top:5%;
        width:50%;
        margin:auto;
    }
    
</style>
{% endblock meta %}

{% block content %}
<form action="{% url 'main:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-container">
        <h2>Create Account</h2>   
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" name="username" id="username"><br>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-at"></i></span>
            </div>
            <input type="email" class="form-control" placeholder="E-mail" name="email" id="email"><br>
        </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
            </div>
            <input type="password" class="form-control" placeholder="Password" name="password" id="password"><br>
        </div>
        <button type="submit" class="btn btn-dark">Sign Up</button>

        <p></p>
        <p>Already have an account? <a href="{% url 'main:login' %}">Log in</a></p>
    </div>
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include "navbar.html" %}
  <div class="container pt-3">
  {% block content %}
  {% endblock content %}
  </div>
</body>

</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet" >
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	
	
	
</head>
<body style="font-family: 'Open Sans', sans-serif;">
	<nav class="navbar navbar-expand-md navbar-dark">
			<a class="navbar-brand" href="/" style="font-size: 30px; font-weight: 700;">Aziz Jabbar Shiddiq</a>
			<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
				<span class="navbar-toggler-icon"></span>
			</button>
		<div class="collapse navbar-collapse" id="navbarMenu">
			
		</div>
    </nav>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>